### ISSUE TITLE
v0.3.5_beta2 好像数据有问题

### ISSUE THREAD

**Issue by aiastia** [Yuzuki999/AWS-Panel#5]
SELECT * FROM `user_data` WHERE (Username = "admin" and password = "¦j»VÙb؇V4n") AND `user_data`.`deleted_at` IS NULL ORDER BY `user_data`.`id` LIMIT 1
[GIN] 2022/03/14 - 11:08:05 | 400 |     686.953µs |   | POST     "/api/v1/User/Login"

**Comment by aiastia** [comment]
v0.3.5_beta 解压后能直接运行 ， v0.3.5_beta2 就提示 这个

**Comment by Yuzuki999** [comment]
新版本已修复
